---
micronaut:
    application:
        name: service-discovery
jackson:
    bean-introspection-module: true

---
consul:
    client:
        registration:
              enabled: true
              check:
                  deregister-critical-service-after: 30s
        defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
